### ISSUE TITLE
document_clustering.py

### ISSUE THREAD

**Issue by ikngoo** [ailabstw/opinion-analysis#1]
真的很感謝您們開源相關工具
line 33: for group_id, group in enumerate(res): 
不知道是否為for group_id, group in enumerate(cluster):

line 35: cluster_df['text'].append(raw_texts[idx])
不知道是否為cluster_df['text'].append(texts[idx])

**Comment by ghost** [comment]
Hi ikngoo,

您的判斷是正確的，
感謝回報，專案已作修正。
